//BEFORE_BATTLE_SELECT
export const TOGGLE_BEFORE_BATTLE_SELECT = 'TOGGLE_BEFORE_BATTLE_SELECT';
export const TOGGLE_BEFORE_BATTLE_HOVER = 'TOGGLE_BEFORE_BATTLE_HOVER';

//GAME_PERIOD
export const BEFORE_BATTLE = 'BEFORE_BATTLE';
export const IN_BATTLE = 'IN_BATTLE';
export const AFTER_BATTLE = 'AFTER_BATTLE';

//ROOM
export const ROOM_FULL = 'ROOM_FULL';
export const CREATE_ROOM = 'CREATE_ROOM';
